### ISSUE TITLE
The style of a text does not get pasted

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#109] opened 2016-06-17 14:44 UTC
If a styled text is copied the style (bold, italics, etc) does not get pasted into the new location.

**Comment by daboe01** [comment] 2016-06-17 17:27
does this only happen when you select text with uniform style?

**Comment by kerusan** [comment] 2016-06-20 10:54
No it happens if I copy some styled text and paste it into another styled text.
![skarmavbild 2016-06-20 kl 12 53 55](https://cloud.githubusercontent.com/assets/783541/16191766/2864e0d8-36e6-11e6-87cc-e53a41d71676.png)

**Comment by daboe01** [comment] 2016-06-20 13:23
@kerusan this should happen only if you have a single style in the pasteboard.
this is actually by design (at the moment).

here is my explanation:
in cocoa we have a plain and a rich pasteboard at the same time.
in cappuccino we currently have only a single pasteboard due to browser-limitations.
i decided to work around this by means of putting rtf on the plain pasteboard.
this makes copy/paste working inside the app and even between two different browsers over the system pasteboard.
however, when i paste into e.g. TextEdit, i get the ugly rtf syntax pasted alongside the text.
for this reason, i decided to put plain text on the pasteboard when a text with a single style is copied and rtf otherwise.

do you have a better idea?

**Comment by kerusan** [comment] 2016-06-21 07:44
Not sure I understand:
What I did was copy the text "proin, this", bold version 13 px and then copied it into the red "Fusce" 18 px. If as you say you are copying rtf, and then paste rtf in again in the same app then the style ought to be retained and the result should look like this pic. But the result was all red 18 px.
![skarmavbild 2016-06-21 kl 09 42 49](https://cloud.githubusercontent.com/assets/783541/16221718/992567f8-3794-11e6-80f2-4ac4406a9acf.png)

**Comment by daboe01** [comment] 2016-06-21 07:48
at the moment only the number of runs in the selection is taken into account, no matter what the attributes are.
it would be possibly better to check whether at least one is not the standard style.
but then: how do we define standard style? this is really a mess.

**Comment by kerusan** [comment] 2016-06-21 09:14
I now see the dilemma. But the handling is not consistent and is confusing for the user. As you imply there is no standard style so copy plain text in one case and rich text in the other case is not a good solution. As I see it for now, is that copy/paste inside the app should be with rich text, and outside the app it  should (sadly) only be possible to copy plain text. Then you probably could save the copied attributed text inside the app. 
I understand that this is kind of messy :-/

**Comment by daboe01** [comment] 2016-06-21 15:42
you can enforce intra-app rich copy/paste by changing line 124 in CPTextView.j to e.g. 
```ObjJ 
        if (stringForPasting._rangeEntries.length > 0)
```

**Comment by daboe01** [comment] 2016-06-21 17:41
have a look at https://github.com/cappuccino/cappuccino/issues/2062 for the underlying issue

**Comment by daboe01** [comment] 2016-06-21 20:24
@kerusan i created https://github.com/daboe01/CPTextView/tree/richpasteexperiments
this branch works well together with PR #2462 
i have to do more testing, though (I.e. the FF codepath)

**Comment by kerusan** [comment] 2016-06-22 09:40
Thanks for pointing out, where in the code it is handled.
I will have a look at the branch.

**Comment by daboe01** [comment] 2016-06-22 20:16
works for me now with https://github.com/cappuccino/cappuccino/pull/2462.
i will keep this one open until https://github.com/cappuccino/cappuccino/pull/2462 is merged into master.

**Comment by kerusan** [comment] 2016-06-23 08:55
Yes works for me to, thank you!
This exactly what I missed before.

**Comment by daboe01** [comment] 2016-06-28 10:30
@kerusan https://github.com/daboe01/CPTextView/issues/98 is about pasting rich text from external editors

**Comment by daboe01** [comment] 2016-06-28 10:31
pasting out is currently impossible (even google docs fails on this)

**Closed** 2016-09-13 20:44 UTC
